name: Deploying on https://xcc-editor.surge.sh

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to Surge
        run: npx surge . --token ${{ secrets.SURGE_TOKEN }} xcc-editor.surge.sh
